version: '3'
services:
  mysql-painting-diary:
    image: mysql:8.0
    container_name: mysql-painting-diary
    ports:
      - "43306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: painting-diary
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - painting-diary-mysql-volume:/var/lib/mysql

volumes:
  painting-diary-mysql-volume:
    driver: local
